//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tShutDownPC.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tShutDownPC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The program allows you to turn off the PC, depending on the selected conditions.
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string AboutTab {
            get {
                return ResourceManager.GetString("AboutTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на License Activation.
        /// </summary>
        public static string Activation {
            get {
                return ResourceManager.GetString("Activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Application settings.
        /// </summary>
        public static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By Audio.
        /// </summary>
        public static string ByAudio {
            get {
                return ResourceManager.GetString("ByAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By CPU.
        /// </summary>
        public static string ByCPU {
            get {
                return ResourceManager.GetString("ByCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable shutdown by Audio activity.
        /// </summary>
        public static string ByCPUAudioBox {
            get {
                return ResourceManager.GetString("ByCPUAudioBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable shutdown by CPU Load.
        /// </summary>
        public static string ByCPUCheckBox {
            get {
                return ResourceManager.GetString("ByCPUCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable shutdown by Microphone activity.
        /// </summary>
        public static string ByCPUMicrophoneBox {
            get {
                return ResourceManager.GetString("ByCPUMicrophoneBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable shutdown by Mouse activity.
        /// </summary>
        public static string ByCPUMouseBox {
            get {
                return ResourceManager.GetString("ByCPUMouseBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By day of the week.
        /// </summary>
        public static string ByDayOfTheWeek {
            get {
                return ResourceManager.GetString("ByDayOfTheWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable PC shutown by day of the week.
        /// </summary>
        public static string ByDayOfTheWeekBox {
            get {
                return ResourceManager.GetString("ByDayOfTheWeekBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By Microphone.
        /// </summary>
        public static string ByMicrophone {
            get {
                return ResourceManager.GetString("ByMicrophone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By mouse.
        /// </summary>
        public static string ByMouse {
            get {
                return ResourceManager.GetString("ByMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By timer.
        /// </summary>
        public static string ByTimer {
            get {
                return ResourceManager.GetString("ByTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable shutdown by timer.
        /// </summary>
        public static string ByTimerCheckBox {
            get {
                return ResourceManager.GetString("ByTimerCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DisableInternet.
        /// </summary>
        public static string DisableInternetType {
            get {
                return ResourceManager.GetString("DisableInternetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Firday.
        /// </summary>
        public static string FridayTB {
            get {
                return ResourceManager.GetString("FridayTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On close hide in tray.
        /// </summary>
        public static string HideInTray {
            get {
                return ResourceManager.GetString("HideInTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EN.
        /// </summary>
        public static string LanEn {
            get {
                return ResourceManager.GetString("LanEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на РУ.
        /// </summary>
        public static string LanRu {
            get {
                return ResourceManager.GetString("LanRu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logout.
        /// </summary>
        public static string LogoutType {
            get {
                return ResourceManager.GetString("LogoutType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main.
        /// </summary>
        public static string MainTab {
            get {
                return ResourceManager.GetString("MainTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Monday.
        /// </summary>
        public static string MondayTB {
            get {
                return ResourceManager.GetString("MondayTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warn for (seconds).
        /// </summary>
        public static string NotifyFor {
            get {
                return ResourceManager.GetString("NotifyFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reboot.
        /// </summary>
        public static string RebootType {
            get {
                return ResourceManager.GetString("RebootType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saturday.
        /// </summary>
        public static string SaturdayTB {
            get {
                return ResourceManager.GetString("SaturdayTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save settings.
        /// </summary>
        public static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string SettingsTab {
            get {
                return ResourceManager.GetString("SettingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose &quot;shutdown&quot; type.
        /// </summary>
        public static string ShutdownGroup {
            get {
                return ResourceManager.GetString("ShutdownGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shutdown.
        /// </summary>
        public static string ShutdownType {
            get {
                return ResourceManager.GetString("ShutdownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sleep.
        /// </summary>
        public static string SleepType {
            get {
                return ResourceManager.GetString("SleepType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sunday.
        /// </summary>
        public static string SundayTB {
            get {
                return ResourceManager.GetString("SundayTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thursday.
        /// </summary>
        public static string ThursdayTB {
            get {
                return ResourceManager.GetString("ThursdayTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PC Shutdown program.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tuesday.
        /// </summary>
        public static string TuesdayTB {
            get {
                return ResourceManager.GetString("TuesdayTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wednesday.
        /// </summary>
        public static string WednesdayTB {
            get {
                return ResourceManager.GetString("WednesdayTB", resourceCulture);
            }
        }
    }
}
